ifconfig="ipconfig"
alias tail="tail -n 50"
alias head="head -n 50"
alias please="sudo"
alias restart="sudo shutdown -r now"
alias reboot="sudo shutdown -r now"
alias halt="sudo shutdown -h now"
alias artisan="php artisan"
